#!/bin/bash
echo "Compilant..."
g++ -o main *.cpp &&

echo "Executant Padro Curt...."
time ./main < inPadroCurtMeu.txt $> outPadroCurtMeu.txt
echo " "

echo "Executant Padro Llarg...."
time ./main < inPadroLlargMeu.txt $> outPadroLlargMeu.txt
echo " "

echo "Diferencies Padro Curt:"
diff outPadroCurt.txt outPadroCurtMeu.txt
echo " "

echo "Diferencies Padro Llarg:"
diff outPadroLlarg.txt outPadroLlargMeu.txt
echo " "

