#!/bin/bash
./scriptCompilacio

echo "Executant Programa (opcio -r)..."
for i in $(seq 1 10);
do
  mida="$((4 + RANDOM%100))"
  echo "Execucio $i (avions: $mida)"
  ./main -r $mida 
  echo ""
done
echo "Executant Programa (opcio -c)..."
./main -c
echo ""

echo "Esborrant executable..."
echo ""
rm main
